/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViagensRouteImport } from './routes/viagens'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as RotasDisponiveisRouteImport } from './routes/rotas-disponiveis'
import { Route as RotasRouteImport } from './routes/rotas'
import { Route as MotoristasRouteImport } from './routes/motoristas'
import { Route as MeusInteressesRouteImport } from './routes/meus-interesses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InteressesRouteImport } from './routes/interesses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardVinculadoRouteImport } from './routes/dashboard.vinculado'
import { Route as DashboardFrotaRouteImport } from './routes/dashboard.frota'
import { Route as DashboardAutonomoRouteImport } from './routes/dashboard.autonomo'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const ViagensRoute = ViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const RotasDisponiveisRoute = RotasDisponiveisRouteImport.update({
  id: '/rotas-disponiveis',
  path: '/rotas-disponiveis',
  getParentRoute: () => rootRouteImport,
} as any)
const RotasRoute = RotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasRoute = MotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusInteressesRoute = MeusInteressesRouteImport.update({
  id: '/meus-interesses',
  path: '/meus-interesses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InteressesRoute = InteressesRouteImport.update({
  id: '/interesses',
  path: '/interesses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVinculadoRoute = DashboardVinculadoRouteImport.update({
  id: '/dashboard/vinculado',
  path: '/dashboard/vinculado',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFrotaRoute = DashboardFrotaRouteImport.update({
  id: '/dashboard/frota',
  path: '/dashboard/frota',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAutonomoRoute = DashboardAutonomoRouteImport.update({
  id: '/dashboard/autonomo',
  path: '/dashboard/autonomo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interesses': typeof InteressesRoute
  '/login': typeof LoginRoute
  '/meus-interesses': typeof MeusInteressesRoute
  '/motoristas': typeof MotoristasRoute
  '/rotas': typeof RotasRoute
  '/rotas-disponiveis': typeof RotasDisponiveisRoute
  '/veiculos': typeof VeiculosRoute
  '/viagens': typeof ViagensRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/autonomo': typeof DashboardAutonomoRoute
  '/dashboard/frota': typeof DashboardFrotaRoute
  '/dashboard/vinculado': typeof DashboardVinculadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interesses': typeof InteressesRoute
  '/login': typeof LoginRoute
  '/meus-interesses': typeof MeusInteressesRoute
  '/motoristas': typeof MotoristasRoute
  '/rotas': typeof RotasRoute
  '/rotas-disponiveis': typeof RotasDisponiveisRoute
  '/veiculos': typeof VeiculosRoute
  '/viagens': typeof ViagensRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/autonomo': typeof DashboardAutonomoRoute
  '/dashboard/frota': typeof DashboardFrotaRoute
  '/dashboard/vinculado': typeof DashboardVinculadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interesses': typeof InteressesRoute
  '/login': typeof LoginRoute
  '/meus-interesses': typeof MeusInteressesRoute
  '/motoristas': typeof MotoristasRoute
  '/rotas': typeof RotasRoute
  '/rotas-disponiveis': typeof RotasDisponiveisRoute
  '/veiculos': typeof VeiculosRoute
  '/viagens': typeof ViagensRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/autonomo': typeof DashboardAutonomoRoute
  '/dashboard/frota': typeof DashboardFrotaRoute
  '/dashboard/vinculado': typeof DashboardVinculadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/interesses'
    | '/login'
    | '/meus-interesses'
    | '/motoristas'
    | '/rotas'
    | '/rotas-disponiveis'
    | '/veiculos'
    | '/viagens'
    | '/dashboard/admin'
    | '/dashboard/autonomo'
    | '/dashboard/frota'
    | '/dashboard/vinculado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/interesses'
    | '/login'
    | '/meus-interesses'
    | '/motoristas'
    | '/rotas'
    | '/rotas-disponiveis'
    | '/veiculos'
    | '/viagens'
    | '/dashboard/admin'
    | '/dashboard/autonomo'
    | '/dashboard/frota'
    | '/dashboard/vinculado'
  id:
    | '__root__'
    | '/'
    | '/interesses'
    | '/login'
    | '/meus-interesses'
    | '/motoristas'
    | '/rotas'
    | '/rotas-disponiveis'
    | '/veiculos'
    | '/viagens'
    | '/dashboard/admin'
    | '/dashboard/autonomo'
    | '/dashboard/frota'
    | '/dashboard/vinculado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InteressesRoute: typeof InteressesRoute
  LoginRoute: typeof LoginRoute
  MeusInteressesRoute: typeof MeusInteressesRoute
  MotoristasRoute: typeof MotoristasRoute
  RotasRoute: typeof RotasRoute
  RotasDisponiveisRoute: typeof RotasDisponiveisRoute
  VeiculosRoute: typeof VeiculosRoute
  ViagensRoute: typeof ViagensRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAutonomoRoute: typeof DashboardAutonomoRoute
  DashboardFrotaRoute: typeof DashboardFrotaRoute
  DashboardVinculadoRoute: typeof DashboardVinculadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viagens': {
      id: '/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof ViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotas-disponiveis': {
      id: '/rotas-disponiveis'
      path: '/rotas-disponiveis'
      fullPath: '/rotas-disponiveis'
      preLoaderRoute: typeof RotasDisponiveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotas': {
      id: '/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof RotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas': {
      id: '/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof MotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-interesses': {
      id: '/meus-interesses'
      path: '/meus-interesses'
      fullPath: '/meus-interesses'
      preLoaderRoute: typeof MeusInteressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interesses': {
      id: '/interesses'
      path: '/interesses'
      fullPath: '/interesses'
      preLoaderRoute: typeof InteressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vinculado': {
      id: '/dashboard/vinculado'
      path: '/dashboard/vinculado'
      fullPath: '/dashboard/vinculado'
      preLoaderRoute: typeof DashboardVinculadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/frota': {
      id: '/dashboard/frota'
      path: '/dashboard/frota'
      fullPath: '/dashboard/frota'
      preLoaderRoute: typeof DashboardFrotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/autonomo': {
      id: '/dashboard/autonomo'
      path: '/dashboard/autonomo'
      fullPath: '/dashboard/autonomo'
      preLoaderRoute: typeof DashboardAutonomoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InteressesRoute: InteressesRoute,
  LoginRoute: LoginRoute,
  MeusInteressesRoute: MeusInteressesRoute,
  MotoristasRoute: MotoristasRoute,
  RotasRoute: RotasRoute,
  RotasDisponiveisRoute: RotasDisponiveisRoute,
  VeiculosRoute: VeiculosRoute,
  ViagensRoute: ViagensRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAutonomoRoute: DashboardAutonomoRoute,
  DashboardFrotaRoute: DashboardFrotaRoute,
  DashboardVinculadoRoute: DashboardVinculadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
